#define SLAB_BIN_COUNT (5)
#define SLAB_MIN_SIZE_LOG2 (5)
#define SLAB_CACHE_TABLE_MAX_SIZE (2048)
#define SLAB_RETURN_TO_HOST_THRESHOLD (2048)
#define SLAB_RETURN_TO_HOST_SIZE (512)
#define SLAB_FETCH_FROM_HOST_SIZE (512)

#define SIGNAL_REQUEST (0)
#define SIGNAL_RETURN (1)
#define SIGNAL_QUERY_AVAILABLE_HEAD_PTR (2)
#define SIGNAL_QUERY_RETURN_TAIL_PTR (3)
#define SIGNAL_RESP_AVAILABLE_HEAD_PTR (4)
#define SIGNAL_RESP_RETURN_TAIL_PTR (5)
#define SIGNAL_GRANT (6)
#define SIGNAL_INIT_SLAB (7)

#define CLIENT_REQUEST_PUT (1)
#define CLIENT_REQUEST_GET (2)

#define ADD_KEY_SIZE (4)
#define AddKeyType uint
  
